// Generated by CoffeeScript 1.4.0
var app, express, http, path;

express = require('express');

http = require('http');

path = require('path');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/../views');
  app.set('view engine', 'jade');
  app.use(require('connect-assets')());
  app.use(require('stylus').middleware(__dirname + '/../public'));
  app.use(express["static"](path.join(__dirname, '/../public')));
  app.use(app.router);
  return app.use(express.errorHandler());
});

app.get('/', function(req, res) {
  return res.render('index', {
    title: 'play'
  });
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log('Express server listening on port ' + app.get('port'));
});
